SELECT @@transaction_isolation;

SET AUTOCOMMIT = 0;
-- SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
-- SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

-- START TRANSACTION;

-- SELECT * FROM payment;

-- UPDATE payment
-- SET amount = 200
-- WHERE payment_id = 5;

-- ROLLBACK;

-- SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;

-- START TRANSACTION;

-- SELECT * FROM payment;

-- COMMIT;


SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;

START TRANSACTION;

SELECT * FROM payment;

UPDATE payment
SET amount = 400
WHERE payment_id = 6;

COMMIT;
ROLLBACK;